const salaryZlecenia = "26.4 ZL нетто/годину💸 (Від 60.000 грн на місяць)";
const salaryUmowaOPrace = "4600 ZL/brutto в місяць💸 (Від 60.000 грн на місяць)";
const studentsSalary = "30.5 ZL нетто/годину💸 (від 70.000 грн на місяць)";

export const allVacancies = [
  {
    rewievs: {
      name: "Катерина",
      images: [],
      date: "11.01.2025",
      vacancy: "Valeo",
      review:
        "Дякую за допомогу з пошуком роботи! Менеджери завжди на зв’язку, допомагали на кожному етапі. Житло чисте та зручне, а умови на роботі навіть кращі, ніж очікувала. Дуже задоволена та рекомендую!",
    },
    title: "Пакування автомобільних фар",
    pageTitle: " ✨ Запрошуємо на вакансію : Пакувальник автомобільних фар для таких автомобілей як : 'Mersedes' 'Audi' 'BMW' ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Valeo",
    city: "Chrzanów (30 км від Краків)",
    contract: "Umowa o pracę",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess:
        " Процес Montaż: Ви будете частиною команди з 6 осіб, що займається перевіркою фар. Кожен виконує свою частину роботи, щоб забезпечити високу якість кінцевого продукту. 🛠️✨",
      secondProcess:
        " Процес Kontrola Jakości: Остаточний контроль якості готових фар. Спокійний темп, перевірка, наклеювання штрих-коду та упаковка. 📦🔍",
      thirdProcess: null,
      fourthProcess: null,
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Наталія",
      images: [],
      date: "08.12.2024",
      vacancy: " 'Bolsius' - виготовлення свічок",
      review:
        "Все пройшло просто чудово! Переїзд, оформлення документів та поселення – все швидко та без проблем. Робота цікава, колектив доброзичливий. Моя подяка менеджерам за підтримку!",
    },
    title: "Пакування свічок",
    pageTitle: " ✨ Запрошуємо на вакансію : Виготовлення свічок та ароматизаторів ✨",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Bolsius",
    city: "Krotoszyn (120 км від Вроцлав)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Пакування свічок по картонним коробкам ✨",
      secondProcess: " Візуальний контроль якості виготовленної продукції 🔍",
      thirdProcess: " Слідкувати за чистотою на робочому місці ✨",
      fourthProcess: null,
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Анна",
      images: [],
      date: "27.09.2024",
      vacancy: "' Пакування одягу 'Nike' ",
      review:
        "Все дуже сподобалося! Завдяки команді швидко оформили документи, допомогли з транспортом і поселенням. На роботу вийшла уже наступного тижня. Компанія та умови проживання — супер. Дуже вдячна!",
    },
    title: "Пакування одягу",
    pageTitle: " ✨ Запрошуємо на вакансію : Пакування одягу на сучайний склад! ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "H&M",
    city: "Wrocław ",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Сортування, маркування, упаковка одягу 📦",
      secondProcess: " Збір та комплектація замовлень 🧺",
      thirdProcess: " Розпаковка/перепаковка товару 📥",
      fourthProcess: " Розміщення товарів на полицях, вішалках 🗂️",
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Степан",
      images: [],
      date: "14.04.2022",
      vacancy: "Mondelez - пакування кондитерських виробів",
      review:
        "Рекомендую цю компанію! Підтримка від менеджерів була на кожному етапі, а житло — комфортне та з усіма зручностями. Почав працювати на пакування цукерок, і все відповідає опису вакансії. Дякую за чудову організацію!",
    },
    title: "Пакування кондитерських виробів",
    pageTitle: " ✨ Запрошуємо на вакансію : Виготовлення та пакування кондитерських виробів ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Mondelez",
    city: "Skarbimierz (60 км від Вроцлав)",
    contract: "Umowa o pracę",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: "Робота на виробничій лінії з різними видами продукції 🍫",
      secondProcess: " Укладка цукерок на лінії 🍬",
      thirdProcess: " Обслуговування конвеєрної лінії та упаковка готової продукції 📦",
      fourthProcess: null,
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Наталія",
      images: [],
      date: "28.11.2024",
      vacancy: "Instanta - пакування чаю та кави",
      review:
        "Дуже задоволена вибором компанії для роботи в Польщі! Мене оформили швидко, підтримка менеджерів на висоті. Житло дуже комфортне, а умови праці відмінні. Була приємно вражена. Рекомендую!",
    },
    title: "Пакування чаю та кави",
    pageTitle: "✨ Запрошуємо на вакансію : Пакування чаю та кави ✨",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Instanta",
    city: "Żory (50 км від Катовіце)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Сортування, пакування кави, чаю 📦",
      secondProcess: " Слідкувати за чистотою на робочому місці 🧺",
      thirdProcess: " Візуальний контроль якості товару 📥",
      fourthProcess: null,
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Андрій",
      images: [],
      date: "13.04.2025",
      vacancy: "Graal",
      review:
        "Чудова підтримка від менеджерів, які надають допомогу на всіх етапах. Оформлення пройшло легко, робота і житло відповідає обіцянкам. Співпрацею дуже задоволений!",
    },
    title: "Пакування лосося",
    pageTitle: " ✨ Запрошуємо на вакансію : Пакувальник червоної риби ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Graal",
    city: "Slupsk",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "700 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Пакування свіжої та копченої продукції 🐟",
      secondProcess: " Контроль якості ✅",
      thirdProcess: " Дотримання техніки безпеки 🦺",
      fourthProcess: null,
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Сергій",
      images: [],
      date: "07.02.2025",
      vacancy: "Whirpool",
      review:
        "Робота з цією компанією — одне задоволення! Менеджери дійсно піклуються про працівників, допомогли з документами та квитками. Житло комфортне, робота цікава. Дякую!",
    },
    title: "Виготовлення побутової техніки",
    pageTitle: " ✨ Запрошуємо на вакансію : Виготовлення побутової техніки ✨",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Whirpool",
    city: "Lodz",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Монтаж компонентів: корзинки, провода, таймери, кнопки, ущільнювачі 📌",
      secondProcess: " Контроль якості: візуальний огляд, наклеювання етикеток, пакування готових виробів 🗂️",
      thirdProcess:
        " Процес монтажу: підготовка і встановлення компонентів у сушильні машини/плити на конвеєрі, контроль виконаної операції 🦺",
      fourthProcess: " Підтримка чистоти на робочому місці 🧺",
      fifthProcess: "",
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "Безкоштовний робочий одяг : 2 футболки, штани, кофти, рукавички, зручне робоче взуття 👕",
    },
  },

  {
    rewievs: {
      name: "Ілона",
      images: [],
      date: "09.05.2025",
      vacancy: "Barlinek",
      review:
        "Дякую за чудову організацію роботи в Польщі! З менеджерами завжди на зв’язку, вони відповіли на всі мої питання. Робота подобається, житло чисте та сучасне.",
    },
    title: "Виготовлення паркетної дошки",
    pageTitle: " ✨ Запрошуємо на вакансію : Виробництво паркетних дошок. Світовий лідер виробництва в цій галузі ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Barlinek",
    city: "Barlinek (30 км від Гожув Великопольскій)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Відділ нарізки сировини: сортування нарізаного сировини та відправка на сушку ✅ ",
      secondProcess:
        "Відділ контролю якості : сортування, чистка верхнього шару дошок. Менше фізичних зусиль, більше уваги та концентрації 🔍",
      thirdProcess: " Склад готової продукції: упаковка та підготовка продукції до перевезення. 📦",
      fourthProcess: null,
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, штани, рукавички, зручне робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Інна",
      images: [],
      date: "22.04.2025",
      vacancy: "Philips",
      review:
        "Найкраща компанія, з якою співпрацював! Житло чисте, сучасне, робота близько. Менеджер був дуже уважний, допоміг вирішити всі питання. Рекомендую усім, хто хоче працювати в Польщі",
    },
    title: "Пакування лампочок 'Philips'",
    pageTitle: " ✨ Запрошуємо на роботу: Пакувальник лампочок та освітлювальних елементів ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Philips",
    city: "Ketzin (250 км від Варшави)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Візуальний контроль якості продукції 💡 ",
      secondProcess: " Пакування готової продукції по коробкам 📦 ",
      thirdProcess: " Участь в збиранні освітлювалних приборів 🔍",
      fourthProcess: null,
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Анатолій",
      images: [],
      date: "18.02.2025",
      vacancy: "Norma Group",
      review:
        "Рекомендую цю компанію! Все пройшло гладко, умови праці хороші, і житло відповідає опису. Окремо дякую менеджерам за оперативність і постійну підтримку!",
    },
    title: "Виготовлення та пакування деталей до автомобілей",
    pageTitle: " ✨ Запрошуємо на роботу: Пакувальник автомобільних деталей (ручки, зажими, двірники, емблеми і т.п.) ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Norma Group",
    city: " Pilica (50 км від Катовіце)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Вставляти металеві деталі в обладнання 🔹",
      secondProcess: "  Після обробки – діставати, перевіряти якість 🔍",
      thirdProcess: " Упаковувати деталі після перевірки 📦",
      fourthProcess: null,
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Володимир",
      images: [],
      date: "04.11.2024",
      vacancy: "Wedel",
      review:
        "Нарешті знайшов роботу за кордоном, де все організовано як слід! Кожен етап — від оформлення документів до поселення — пройшов легко. Дякую за підтримку та чесний підхід!",
    },
    title: "Пакування кондитерських виробів",
    pageTitle: " ✨ Запрошуємо на роботу: Пакування кондитерських виробів ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Wedel",
    city: "Warszawa",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "800 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Сортування, зважування, та пакування кондитерських виробів 🍫 ",
      secondProcess: "Слідкувати за чистотою на робочому місці 🔍 ",
      thirdProcess: null,
      fourthProcess: null,
      fifthProcess: null,
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Сергій",
      images: [],
      date: "14.05.2025",
      vacancy: "Pantos UDT",
      review:
        "Не очікував, що все буде настільки просто. Мені допомогли з усім — від документів до адаптації на місці. Робота нормальна, житло — комфортне. Рекомендую тим, хто шукає надійну підтримку за кордоном.",
    },
    title: "Карщик UDT",
    pageTitle: " ✨ Запрошуємо на роботу карщиків з правами UDT. Досвід не обов’язковий ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Pantos UDT",
    city: "Wrocław",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "450 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Робота на фронтальному навантажувачі – 80% часу 📦",
      secondProcess: " Завантаження/розвантаження товару 🚚",
      thirdProcess: "  Виконання замовлень на відправку 📑",
      fourthProcess: " Інвентаризація, контроль безпеки 📊 ",
      fifthProcess: "",
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, штани, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Ігор",
      images: [],
      date: "19.08.2024",
      vacancy: " Автомобільний завод ZF ",
      review:
        "Сервіс чудовий, менеджери відповідальні та завжди на зв'язку. На місці нас зустріли, все показали, пояснили. Житло хороше, з усіма умовами для комфортного проживання. На роботу вийшов швидко і дуже задоволений!",
    },
    title: "Комплектація рульової системи автомобіля",
    pageTitle: "✨ Запрошуємо на роботу : Працівників на лінію. Потрібно збирати рульові системи для автомобілів ✨ ",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Czechowice-Dziedzice",
    city: "Czechowice-Dziedzice (50 км від Катовіце)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Монтаж колон, планок, систем безпеки 📦",
      secondProcess: " Контроль якості деталей 🔍",
      thirdProcess: "",
      fourthProcess: "",
      fifthProcess: "",
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Катя",
      images: [],
      date: "07.05.2024",
      vacancy: "Pol Plast",
      review:
        "Співпрацею дуже задоволений. Умови на роботі точно відповідають опису, а житло просторе та комфортне. Дуже вдячний менеджерам за терпіння та професійність!",
    },
    title: " Пакування підводних масок",
    pageTitle: "✨ Запрошуємо на роботу : Пакувальник підводних масок ✨",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Pol Plast",
    city: " Myślenice (30 км від Краків)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess:
        " Комплектування масок (маски на лінії їдуть в розібраному вигляді, кожен працівник займається з'єднанням певних деталей) ✅",
      secondProcess: " Візуальний контроль якості 🔍",
      thirdProcess: " Пакування готової продукції. Цей процес виконується сидячи 📥",
      fourthProcess: "",
      fifthProcess: "",
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Маша",
      images: [],
      date: "10.01.2025",
      vacancy: "Adient",
      review:
        "Залишилася задоволена співпрацею! Мене зустріли, все пояснили та підтримували на кожному кроці. Житло комфортне, а умови роботи такі, як обіцяли. Дякую команді за турботу",
    },
    title: "Виготовлення автомобільних сидінь",
    pageTitle: "✨ Запрошуємо на роботу : Виробництво автомобільних сидінь ✨",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Adient",
    city: "Świebodzin (110 км від Познань)",
    contract: "Umowa o pracę",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Вставити деталь, перевірити, передати далі 🔧",
      secondProcess: " Складання/Монтаж – електроінструмент 🔧",
      thirdProcess: " Упаковка – вкласти у контейнер, наклеїти етикетку 🗂️",
      fourthProcess: "",
      fifthProcess: "",
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Світлана",
      images: [],
      date: "17.04.2024",
      vacancy: "Виробництво устілок для взуття",
      review:
        "Дуже вдячна за допомогу з пошуком роботи! Менеджери — справжні професіонали, завжди були на зв’язку і все чітко пояснили. Житло чисте, комфортне, навіть краще, ніж очікувала. На роботі — чудовий колектив і гарні умови. Буду рекомендувати всім знайомим",
    },
    title: "Виробництво устілок для взуття",
    pageTitle: "✨ Запрошуємо на роботу : Виробництво та пакування устілок для взуття! ✨",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Jorno",
    city: "Jaworzno (18 км від Katowice)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Обрізання зайвих частинок тканини ✂️",
      secondProcess: " Контроль якості 🔍 ",
      thirdProcess: " Пакування у коробки 📦",
      fourthProcess: "",
      fifthProcess: "",
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Георгій",
      images: [],
      date: "21.03.2025",
      vacancy: " Виробництво косметики ",
      review:
        "Я вперше працюю за кордоном і трохи хвилювався, але менеджери допомогли з усіма питаннями, навіть із побутовими дрібницями. Житло чудове, є всі необхідні умови, а на підприємстві привітний колектив. Дякую за турботу та професійний підхід!",
    },
    title: "Пакування косметики",
    pageTitle: "✨ Запрошуємо на роботу : Пакувальник косметики ✨",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "Nuko",
    city: "Garwolin (50 км від Варшава)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Сортування, маркування, упаковка косметики 💄",
      secondProcess: " Візуальний контроль якості 🛂",
      thirdProcess: "",
      fourthProcess: "",
      fifthProcess: "",
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },

  {
    rewievs: {
      name: "Лілія",
      images: [],
      date: "03.05.2025",
      vacancy: "Склад DIY Logistic",
      review:
        "Все супер! Умови роботи точно такі, як мені описали на початку. Проживання хороше, без проблем. Менеджери допомогли із квитками, на всі питання відповідають. Дуже вдячна!",
    },
    title: "Пакування товарів на складі",
    pageTitle: " Запрошуємо на роботу: Комплектування різних товарів на складі",
    img: {
      hostelFoto: [],
      vacancyFoto: [],
    },
    name: "DIY Logistic Services Polska",
    city: "Świebodzin (110 км від Познань)",
    contract: "Umowa zlecenia",
    salary: {
      salaryPerHour: null,
      studentsSalary: null,
      salaryPerMonth: null,
      night: "+20% до ставки 🌙",
      overtime: "+50% до ставки ⏱️",
      weekendWork: "+100% до ставки 🎉",
    },
    workingHours: "8-12 годин в день (5-6 днів на тиждень)",
    premiums: "500 зл брутто за продуктивність та відсутність прогулів 💸",
    responsibilities: {
      firstProcess: " Приймання, транспортування та розміщення вантажів 📦",
      secondProcess: " Комплектація та пакування замовлень. Робота зі сканерами 📲",
      thirdProcess: " Використання ручних візків та допоміжного обладнання 🛒",
      fourthProcess: " Використання інструментів (ножі, ваги, етикетувальні машини тощо) ⚙️",
      fifthProcess: "Робота з триступеневою драбиною (до 1 м) ",
    },
    hostel: "Безкоштовно. 2-4 людини в кімнаті",
    requirements: {
      gender: "Чоловіки, Жінки, Пари 👩",
      experience: "Беремо кандидатів навіть без досвіду роботи в Польщі 🌱",
      proficiency: "Не обов’язково",
      added: "БЕЗКОШТОВНИЙ робочий одяг (футболка, перчатки, робоче взуття) 👕",
    },
  },
];
